# Generated by Django 5.0.3 on 2024-05-23 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_rename_residents_room_residents_alter_room_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="rid",
            new_name="room_id",
        ),
    ]
