# Generated by Django 5.0.3 on 2024-05-23 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_rename_rid_room_room_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="room_id",
            new_name="rid",
        ),
    ]
