# Generated by Django 5.0.3 on 2024-07-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0006_inventoryitem_inventorylist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorylist",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
