# Generated by Django 5.0.3 on 2024-07-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_alter_inventorylist_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="residents",
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="residents",
            field=models.IntegerField(
                max_length=1, verbose_name="Number of Residents/Beds"
            ),
        ),
    ]
