# Generated by Django 5.0.3 on 2024-07-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0008_remove_room_residents_alter_roomtype_residents"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_occupants",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
