# Generated by Django 5.0.3 on 2024-07-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0009_room_current_occupants"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="roomtype_images/"
            ),
        ),
    ]
