# Generated by Django 5.0.3 on 2024-07-25 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0010_roomtype_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="current_occupants",
        ),
        migrations.AddField(
            model_name="room",
            name="current_occupants",
            field=models.ManyToManyField(
                blank=True, related_name="rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
