# Generated by Django 5.0.3 on 2024-05-07 18:08

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0003_hostelfeatures_hostelgallery_hotelfaqs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
