# Generated by Django 5.0.7 on 2024-08-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0005_announcements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
