# Generated by Django 5.0.3 on 2024-05-22 17:39

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hostel", "0004_alter_hostel_description"),
        ("rooms", "0003_rename_residents_room_residents_alter_room_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("Processing", "Processing"),
                            ("cancelled", "cancelled"),
                            ("initiated", "initiated"),
                            ("failed", "failed"),
                            ("refunding", "refunding"),
                            ("refunded", "refunded"),
                            ("unpaid", "Unpaid"),
                            ("expired", "expired"),
                        ],
                        max_length=100,
                    ),
                ),
                ("full_name", models.CharField(max_length=1000)),
                ("email", models.EmailField(max_length=1000)),
                ("phone", models.CharField(max_length=1000)),
                (
                    "before_discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "saved",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_payment_intent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "success_id",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "booking_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=" abcdefghijkImnopqrstuvwxyz",
                        length=10,
                        max_length=20,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostel.hostel",
                    ),
                ),
                ("room", models.ManyToManyField(to="rooms.room")),
                (
                    "room_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rooms.roomtype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
