# Generated by Django 5.0.3 on 2024-05-22 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="check_in_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="check_out_date",
        ),
    ]
