# Generated by Django 5.0.3 on 2024-05-23 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_remove_booking_check_in_date_and_more"),
        ("rooms", "0004_rename_rid_room_room_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="room",
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rooms.room",
            ),
        ),
    ]
