# Generated by Django 5.0.3 on 2024-05-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_rename_room_booking_room_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="room_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
