# Generated by Django 5.0.3 on 2024-06-12 09:36

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_alter_booking_success_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijkImnopqrstuvwxyz",
                length=10,
                max_length=20,
                prefix="",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="success_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijkImnopqrstuvwxyz",
                blank=True,
                length=10,
                max_length=20,
                null=True,
                prefix="",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Booking Confirmed", "Booking Confirmed"),
                            ("Booking Cancelled", "Booking Cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
                ("seen", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="booking.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
