# Generated by Django 5.0.3 on 2024-07-27 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_alter_booking_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="room_id",
        ),
    ]
