# Generated by Django 5.0.7 on 2024-08-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_remove_booking_room_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="room_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
