# Generated by Django 5.0.3 on 2024-07-24 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_alter_inventorylist_slug"),
        ("userDashboard", "0002_fault"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fault",
            name="faulty_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faults",
                to="rooms.inventoryitem",
                verbose_name="Faulty Item",
            ),
        ),
    ]
