# Generated by Django 5.0.3 on 2024-07-24 01:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userDashboard", "0003_alter_fault_faulty_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fault",
            name="inventory_list",
        ),
    ]
