# Generated by Django 5.0.3 on 2024-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="wallet",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
